# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task4UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 971)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(0, 0, 0);\n"
"}\n"
"QPushButton {\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-width: 2px;\n"
"    border-color: rgb(0, 161, 118);\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color:rgb(0, 243, 178)\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QLabel, QAbstractButton{\n"
"    font: bold;\n"
"}\n"
"QGroupBox {\n"
"   \n"
"    font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color:rgb(255, 255, 255);\n"
"    selection-color: rgb(255, 255, 255); \n"
"    selection-background-color: rgb(150, 170, 155);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {    \n"
"    background-color: rgb(150, 170, 155);\n"
"    subcontrol-origin: border; /* important*/\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border: 2px solid rgb(150, 170, 155);\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down:on,\n"
"QComboBox::drop-down:focus {\n"
"/*    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgb(52, 104, 77), stop:1  rgb(0, 255, 183)); rgb(150, 170, 155)*/\n"
"    background-color: rgb(214, 255, 214);\n"
"    border:2px solid rgb(142, 170, 142);\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(214, 255, 214);\n"
"    border: 3px solid rgb(142, 170, 142);\n"
"    border-radius: 8px;\n"
"}\n"
"QRadioButton{\n"
"    color: white;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: 2px solid black;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: rgb(190, 218, 197);\n"
"    border: 1.2px solid #ffffff;\n"
"    border-style: outset;\n"
"    border-radius: 15px;\n"
"}\n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 1px 10px 10px10px;\n"
"    color: rgb(0, 0, 0)\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QSlider,\n"
"QSlider:active,\n"
"QSlider:!active {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider:horizontal {\n"
"    padding: 0px 10px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"QSlider::groove {\n"
"    background-color: rgba(0,0,0,30);\n"
"    border: 1px solid rgba(0,0,0,40);\n"
"    border-radius: 5px;\n"
"    margin: 4px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 8px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 8px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled,\n"
"QSlider::groove:vertical:disabled {\n"
"    border-color:  #5a5a5a;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"\n"
"QSlider::handle:horizontal,\n"
"QSlider::handle:vertical {\n"
"    background-color: #505050;\n"
"    border: 1px solid #505050;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    margin: -4px 0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    margin: 0 -4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover,\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    border-color: #94b30f;\n"
"    background-color: #94b30f;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled,\n"
"QSlider::handle:vertical:disabled {\n"
"    border-color: #5a5a5a;\n"
"    background-color: #5a5a5a;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_img_mixer = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img_mixer.sizePolicy().hasHeightForWidth())
        self.label_img_mixer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_img_mixer.setFont(font)
        self.label_img_mixer.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_img_mixer.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:none;")
        self.label_img_mixer.setScaledContents(False)
        self.label_img_mixer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_mixer.setObjectName("label_img_mixer")
        self.gridLayout_20.addWidget(self.label_img_mixer, 0, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setContentsMargins(0, 6, -1, -1)
        self.gridLayout_17.setHorizontalSpacing(20)
        self.gridLayout_17.setVerticalSpacing(7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.radioButton_Mag_phase = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Mag_phase.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_Mag_phase.setFont(font)
        self.radioButton_Mag_phase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Mag_phase.setStyleSheet("")
        self.radioButton_Mag_phase.setObjectName("radioButton_Mag_phase")
        self.gridLayout_17.addWidget(self.radioButton_Mag_phase, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem, 0, 0, 1, 1)
        self.radioButton_Real_Imaginary = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Real_Imaginary.setMinimumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_Real_Imaginary.setFont(font)
        self.radioButton_Real_Imaginary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_Real_Imaginary.setStyleSheet("")
        self.radioButton_Real_Imaginary.setObjectName("radioButton_Real_Imaginary")
        self.gridLayout_17.addWidget(self.radioButton_Real_Imaginary, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setHorizontalSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"color: white;")
        self.label_2.setIndent(9)
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 23))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_19.addWidget(self.comboBox, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_img1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_img1.setCheckable(False)
        self.groupBox_img1.setObjectName("groupBox_img1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_img1)
        self.gridLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_ftcomp_img1 = QtWidgets.QLabel(self.groupBox_img1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_ftcomp_img1.setFont(font)
        self.label_ftcomp_img1.setStyleSheet("border:none;")
        self.label_ftcomp_img1.setObjectName("label_ftcomp_img1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ftcomp_img1)
        self.comboBox_img1 = QtWidgets.QComboBox(self.groupBox_img1)
        self.comboBox_img1.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_img1.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(9)
        self.comboBox_img1.setFont(font)
        self.comboBox_img1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_img1.setObjectName("comboBox_img1")
        self.comboBox_img1.addItem("")
        self.comboBox_img1.addItem("")
        # self.comboBox_img1.addItem("")
        # self.comboBox_img1.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_img1)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_w1 = QtWidgets.QLabel(self.groupBox_img1)
        self.label_w1.setStyleSheet("border:none;")
        self.label_w1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_w1.setObjectName("label_w1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_w1)
        self.horizontalSlider_img1 = QtWidgets.QSlider(self.groupBox_img1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_img1.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_img1.setSizePolicy(sizePolicy)
        self.horizontalSlider_img1.setMinimumSize(QtCore.QSize(170, 32))
        self.horizontalSlider_img1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_img1.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0,\n"
"        stop:0 rgba(50, 50, 50, 255),\n"
"        stop:1 rgba(142, 170, 142, 255));\n"
"    width: 10px;\n"
"    margin-top: -4px;\n"
"    margin-bottom: -4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(50, 50, 50, 255), stop:1  rgba(142, 170, 142, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border:1px solid rgb(142, 170, 142);\n"
"}")
        self.horizontalSlider_img1.setTracking(True)
        self.horizontalSlider_img1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_img1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_img1.setObjectName("horizontalSlider_img1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_img1)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_img1 = ClickableLabel(self.groupBox_img1)
        self.label_img1.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img1.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"")
        self.label_img1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img1.setLineWidth(1)
        self.label_img1.setText("")
        self.label_img1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img1.setObjectName("label_img1")
        self.gridLayout_2.addWidget(self.label_img1, 0, 0, 1, 1)
        self.label_img1_fft = ClickableViewer(self.groupBox_img1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img1_fft.sizePolicy().hasHeightForWidth())
        self.label_img1_fft.setSizePolicy(sizePolicy)
        self.label_img1_fft.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img1_fft.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img1_fft.setToolTip("")
        self.label_img1_fft.setAccessibleDescription("")
        self.label_img1_fft.setAutoFillBackground(False)
        self.label_img1_fft.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_img1_fft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img1_fft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img1_fft.setObjectName("label_img1_fft")
        self.gridLayout_2.addWidget(self.label_img1_fft, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_img1, 0, 0, 1, 1)
        self.groupBox_img2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_img2.setStyleSheet("/*background-color: rgb(145, 217, 217);*/\n"
"/*background-color: rgb(210, 255, 208);*/\n"
"/*background-color: rgb(176, 255, 212);*/")
        self.groupBox_img2.setObjectName("groupBox_img2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_img2)
        self.gridLayout_11.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_ftcomp_img2 = QtWidgets.QLabel(self.groupBox_img2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_ftcomp_img2.setFont(font)
        self.label_ftcomp_img2.setStyleSheet("border:none;")
        self.label_ftcomp_img2.setObjectName("label_ftcomp_img2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ftcomp_img2)
        self.comboBox_img2 = QtWidgets.QComboBox(self.groupBox_img2)
        self.comboBox_img2.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_img2.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(9)
        self.comboBox_img2.setFont(font)
        self.comboBox_img2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_img2.setObjectName("comboBox_img2")
        self.comboBox_img2.addItem("")
        self.comboBox_img2.addItem("")
        # self.comboBox_img2.addItem("")
        # self.comboBox_img2.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_img2)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_w2 = QtWidgets.QLabel(self.groupBox_img2)
        self.label_w2.setStyleSheet("border:none;")
        self.label_w2.setObjectName("label_w2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_w2)
        self.horizontalSlider_img2 = QtWidgets.QSlider(self.groupBox_img2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_img2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_img2.setSizePolicy(sizePolicy)
        self.horizontalSlider_img2.setMinimumSize(QtCore.QSize(170, 0))
        self.horizontalSlider_img2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_img2.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0,\n"
"        stop:0 rgba(50, 50, 50, 255),\n"
"        stop:1 rgba(142, 170, 142, 255));\n"
"    width: 10px;\n"
"    margin-top: -4px;\n"
"    margin-bottom: -4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(50, 50, 50, 255), stop:1  rgba(142, 170, 142, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border:1px solid rgb(142, 170, 142);\n"
"}")
        self.horizontalSlider_img2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_img2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_img2.setObjectName("horizontalSlider_img2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_img2)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_img2 = ClickableLabel(self.groupBox_img2)
        self.label_img2.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img2.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"")
        self.label_img2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img2.setLineWidth(1)
        self.label_img2.setText("")
        self.label_img2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img2.setObjectName("label_img2")
        self.gridLayout_9.addWidget(self.label_img2, 0, 0, 1, 1)
        self.label_img2_fft = ClickableViewer(self.groupBox_img2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img2_fft.sizePolicy().hasHeightForWidth())
        self.label_img2_fft.setSizePolicy(sizePolicy)
        self.label_img2_fft.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img2_fft.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img2_fft.setToolTip("")
        self.label_img2_fft.setAccessibleDescription("")
        self.label_img2_fft.setAutoFillBackground(False)
        self.label_img2_fft.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_img2_fft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img2_fft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img2_fft.setObjectName("label_img2_fft")
        self.gridLayout_9.addWidget(self.label_img2_fft, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_img2, 0, 1, 1, 1)
        self.groupBox_img3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_img3.setObjectName("groupBox_img3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_img3)
        self.gridLayout_8.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_ftcomp_img3 = QtWidgets.QLabel(self.groupBox_img3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_ftcomp_img3.setFont(font)
        self.label_ftcomp_img3.setStyleSheet("border:none;")
        self.label_ftcomp_img3.setObjectName("label_ftcomp_img3")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ftcomp_img3)
        self.comboBox_img3 = QtWidgets.QComboBox(self.groupBox_img3)
        self.comboBox_img3.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_img3.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(9)
        self.comboBox_img3.setFont(font)
        self.comboBox_img3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_img3.setObjectName("comboBox_img3")
        self.comboBox_img3.addItem("")
        self.comboBox_img3.addItem("")
        # self.comboBox_img3.addItem("")
        # self.comboBox_img3.addItem("")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_img3)
        self.horizontalLayout_3.addLayout(self.formLayout_7)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_w3 = QtWidgets.QLabel(self.groupBox_img3)
        self.label_w3.setStyleSheet("border:none;")
        self.label_w3.setObjectName("label_w3")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_w3)
        self.horizontalSlider_img3 = QtWidgets.QSlider(self.groupBox_img3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_img3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_img3.setSizePolicy(sizePolicy)
        self.horizontalSlider_img3.setMinimumSize(QtCore.QSize(170, 0))
        self.horizontalSlider_img3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_img3.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0,\n"
"        stop:0 rgba(50, 50, 50, 255),\n"
"        stop:1 rgba(142, 170, 142, 255));\n"
"    width: 10px;\n"
"    margin-top: -4px;\n"
"    margin-bottom: -4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(50, 50, 50, 255), stop:1  rgba(142, 170, 142, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border:1px solid rgb(142, 170, 142);\n"
"}")
        self.horizontalSlider_img3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_img3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_img3.setObjectName("horizontalSlider_img3")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_img3)
        self.horizontalLayout_3.addLayout(self.formLayout_8)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_img3 = ClickableLabel(self.groupBox_img3)
        self.label_img3.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img3.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"")
        self.label_img3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img3.setLineWidth(1)
        self.label_img3.setText("")
        self.label_img3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img3.setObjectName("label_img3")
        self.gridLayout_6.addWidget(self.label_img3, 0, 0, 1, 1)
        self.label_img3_fft = ClickableViewer(self.groupBox_img3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img3_fft.sizePolicy().hasHeightForWidth())
        self.label_img3_fft.setSizePolicy(sizePolicy)
        self.label_img3_fft.setMinimumSize(QtCore.QSize(0, 134))
        self.label_img3_fft.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img3_fft.setToolTip("")
        self.label_img3_fft.setAccessibleDescription("")
        self.label_img3_fft.setAutoFillBackground(False)
        self.label_img3_fft.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_img3_fft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img3_fft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img3_fft.setObjectName("label_img3_fft")
        self.gridLayout_6.addWidget(self.label_img3_fft, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_img3, 1, 0, 1, 1)
        self.groupBox_img4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_img4.setObjectName("groupBox_img4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_img4)
        self.gridLayout_16.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_ftcomp_img4 = QtWidgets.QLabel(self.groupBox_img4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_ftcomp_img4.setFont(font)
        self.label_ftcomp_img4.setStyleSheet("border:none;")
        self.label_ftcomp_img4.setObjectName("label_ftcomp_img4")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ftcomp_img4)
        self.comboBox_img4 = QtWidgets.QComboBox(self.groupBox_img4)
        self.comboBox_img4.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_img4.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(9)
        self.comboBox_img4.setFont(font)
        self.comboBox_img4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_img4.setObjectName("comboBox_img4")
        self.comboBox_img4.addItem("")
        self.comboBox_img4.addItem("")
        # self.comboBox_img4.addItem("")
        # self.comboBox_img4.addItem("")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_img4)
        self.horizontalLayout_4.addLayout(self.formLayout_9)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_w4 = QtWidgets.QLabel(self.groupBox_img4)
        self.label_w4.setStyleSheet("border:none;")
        self.label_w4.setObjectName("label_w4")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_w4)
        self.horizontalSlider_img4 = QtWidgets.QSlider(self.groupBox_img4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_img4.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_img4.setSizePolicy(sizePolicy)
        self.horizontalSlider_img4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_img4.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0,\n"
"        stop:0 rgba(50, 50, 50, 255),\n"
"        stop:1 rgba(142, 170, 142, 255));\n"
"    width: 10px;\n"
"    margin-top: -4px;\n"
"    margin-bottom: -4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(50, 50, 50, 255), stop:1  rgba(142, 170, 142, 255));\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"    border:1px solid rgb(142, 170, 142);\n"
"}")
        self.horizontalSlider_img4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_img4.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_img4.setObjectName("horizontalSlider_img4")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_img4)
        self.horizontalLayout_4.addLayout(self.formLayout_10)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_img4 = ClickableLabel(self.groupBox_img4)
        self.label_img4.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img4.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"")
        self.label_img4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_img4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img4.setLineWidth(1)
        self.label_img4.setText("")
        self.label_img4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img4.setObjectName("label_img4")
        self.gridLayout_12.addWidget(self.label_img4, 0, 0, 1, 1)
        self.label_img4_fft = ClickableViewer(self.groupBox_img4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img4_fft.sizePolicy().hasHeightForWidth())
        self.label_img4_fft.setSizePolicy(sizePolicy)
        self.label_img4_fft.setMinimumSize(QtCore.QSize(255, 134))
        self.label_img4_fft.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_img4_fft.setToolTip("")
        self.label_img4_fft.setAccessibleDescription("")
        self.label_img4_fft.setAutoFillBackground(False)
        self.label_img4_fft.setStyleSheet("border: 2px solid rgb(67, 80, 67);\n"
"border-radius: 8px;\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_img4_fft.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img4_fft.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_img4_fft.setObjectName("label_img4_fft")
        self.gridLayout_12.addWidget(self.label_img4_fft, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_img4, 1, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_output = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_output.setMaximumSize(QtCore.QSize(16777215, 390))
        self.groupBox_output.setObjectName("groupBox_output")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_output)
        self.gridLayout_14.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_outputs = QtWidgets.QLabel(self.groupBox_output)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_outputs.setFont(font)
        self.label_outputs.setStyleSheet("border:none;")
        self.label_outputs.setObjectName("label_outputs")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_outputs)
        self.comboBox_outputs = QtWidgets.QComboBox(self.groupBox_output)
        self.comboBox_outputs.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(9)
        self.comboBox_outputs.setFont(font)
        self.comboBox_outputs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_outputs.setObjectName("comboBox_outputs")
        self.comboBox_outputs.addItem("")
        self.comboBox_outputs.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_outputs)
        self.gridLayout_5.addLayout(self.formLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_output1 = ImageView(self.groupBox_output)
        self.label_output1.setMinimumSize(QtCore.QSize(255, 235))
        self.label_output1.setMaximumSize(QtCore.QSize(16777215, 350))
        self.label_output1.setStyleSheet("border: 3px solid rgb(67, 80, 67);\n"
                                         "border-radius: 8px;\n"
                                         "background-color: rgba(255, 255, 255, 0);")
        self.label_output1.setObjectName("label_output1")
        self.horizontalLayout_5.addWidget(self.label_output1)

        self.label_output2 = ImageView(self.groupBox_output)
        self.label_output2.setMinimumSize(QtCore.QSize(255, 235))
        self.label_output2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_output2.setStyleSheet("border: 3px solid rgb(67, 80, 67);\n"
                                         "border-radius: 8px;\n"
                                         "background-color: rgba(255, 255, 255, 0);")
        self.label_output2.setObjectName("label_output2")
        self.label_output1.ui.histogram.hide()
        self.label_output1.ui.roiBtn.hide()
        self.label_output1.ui.menuBtn.hide()
        self.label_output1.axes.clear()
        self.label_output2.ui.histogram.hide()
        self.label_output2.ui.roiBtn.hide()
        self.label_output2.ui.menuBtn.hide()
        self.horizontalLayout_5.addWidget(self.label_output2)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_output)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semiligh")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;")
        self.label.setObjectName("label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(142, 170, 142); /*qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 155, 195, 255), stop:1 rgba(255, 255, 255, 255));*/\n"
"    width: 1px;\n"
"/*    margin: 0px 1px;*/\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.gridLayout_5.addLayout(self.formLayout_6, 2, 0, 1, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_output, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_15, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_img_mixer.setText(_translate("MainWindow", " Image Mixer"))
        self.radioButton_Mag_phase.setText(_translate("MainWindow", "Magnitude - Phase"))
        self.radioButton_Real_Imaginary.setText(_translate("MainWindow", "Real - Imaginary"))
        self.label_2.setText(_translate("MainWindow", "Region of Interest    "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Full region"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Inner region"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Outer region"))
        self.groupBox_img1.setTitle(_translate("MainWindow", "Image 1"))
        self.label_ftcomp_img1.setText(_translate("MainWindow", "FT Components"))
        self.comboBox_img1.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_img1.setItemText(1, _translate("MainWindow", "Phase"))
        # self.comboBox_img1.setItemText(2, _translate("MainWindow", "Real"))
        # self.comboBox_img1.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_w1.setText(_translate("MainWindow", "Weight"))
        self.groupBox_img2.setTitle(_translate("MainWindow", "Image 2"))
        self.label_ftcomp_img2.setText(_translate("MainWindow", "FT Components"))
        self.comboBox_img2.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_img2.setItemText(1, _translate("MainWindow", "Phase"))
        # self.comboBox_img2.setItemText(2, _translate("MainWindow", "Real"))
        # self.comboBox_img2.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_w2.setText(_translate("MainWindow", "Weight"))
        self.groupBox_img3.setTitle(_translate("MainWindow", "Image 3"))
        self.label_ftcomp_img3.setText(_translate("MainWindow", "FT Components"))
        self.comboBox_img3.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_img3.setItemText(1, _translate("MainWindow", "Phase"))
        # self.comboBox_img3.setItemText(2, _translate("MainWindow", "Real"))
        # self.comboBox_img3.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_w3.setText(_translate("MainWindow", "Weight"))
        self.groupBox_img4.setTitle(_translate("MainWindow", "Image 4"))
        self.label_ftcomp_img4.setText(_translate("MainWindow", "FT Components"))
        self.comboBox_img4.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboBox_img4.setItemText(1, _translate("MainWindow", "Phase"))
        # self.comboBox_img4.setItemText(2, _translate("MainWindow", "Real"))
        # self.comboBox_img4.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.label_w4.setText(_translate("MainWindow", "Weight"))
        self.groupBox_output.setTitle(_translate("MainWindow", "Output"))
        self.label_outputs.setText(_translate("MainWindow", "Output"))
        self.comboBox_outputs.setItemText(0, _translate("MainWindow", "Output 1"))
        self.comboBox_outputs.setItemText(1, _translate("MainWindow", "Output 2"))
        self.label.setText(_translate("MainWindow", "Mixing Process"))
from Classes import ClickableViewer
from main import ClickableLabel
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
